language: node_js

node_js:
- '12.16.0'

branches:
  only:
  - hexo                # 只监测 hexo 分支上的 commit

before_install:
- npm install -g hexo-cli # 安装 hexo

install:
- npm install             # 安装额外的插件

script:
- hexo generate

after_success:
- git config --global user.name "yujiuqie"
- git config --global user.email "yujiuqie@163.com"
- hexo deploy